name: CI

on:
  push:
    branches:
      - main
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Convert Insomnia to Postman
        run: npx insomnia-to-postman APITest_GoRest.json APITest_GoRest.postman_collection.json

      - name: Install Newman
        run: npm install -g newman

      - name: Run tests with Newman
        env:
          base_url: https://gorest.co.in/public/v2
          token: ${{ secrets.GOREST_TOKEN }}
        run: newman run APITest_GoRest.postman_collection.json --global-var "base_url=${{ env.base_url }}" --global-var "token=${{ env.token }}"