name: CI

on:
  push:
    branches:
      - main
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Insomnia CLI
        run: npm install -g insomnia-inso

      - name: Run tests
        env:
          GOREST_TOKEN: ${{ secrets.GOREST_TOKEN }}
        run: inso run test Testes_GoRest.json --env "QA - GoRest" --ci
